name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set up Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
        id: go
      - name: Install dependencies
        run: sudo apt-get install build-essential
      - name: Install packages
        run: go mod tidy
      - name: Run Test
        run: make test
      - name: Send coverage to coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out